### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [jr-consulting/kodilla-js8.4-repository#1]
- [x] dodaj doctype
- [x] usun niepotrzebne spacje z `<title>`
- [x] w js masz w niektorych miejscach za duzo spacji, wystarczy jedna np `'Podaj rozmiar podstawy trójkata w cm:  '` (na koncu 2 spacje)
- [x] jesli nie uzywasz css to go nie dolaczaj w html

**Comment by jr-consulting** [comment]
Poprawione

**Comment by zdolny** [comment]
- [ ] nadal dolaczasz nieistniejacy plik css w html'u
- [ ] plik `.gitignore` uzywa sie do ignorowania plikow, ktore nie chcesz zeby znalazly sie w repo z powodow takich jak:
- pliki tymczasowe edytorow kodu
- pliki systemowe
- zaleznosci developerskie, ktore kazdy moze pobrac samemu
itp
raczej nie stosowalbym go do ignorowania katalogu css/ - mozesz po prostu usunac ten katalog z repo, jesli nie jest potrzebny

**Comment by jr-consulting** [comment]
Done

**Comment by zdolny** [comment]
super
